export const products = [
  {
    name: "Basic Men T-Shirt",
    gender: "men",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
    ],
    price: 19.99,
    description: "A simple t-shirt available in various sizes and colors.",
  },
  {
    name: "Striped Men T-Shirt",
    gender: "men",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 19.99,
    description: "A striped t-shirt available in various sizes and colors.",
  },
  {
    name: "Quality Men T-Shirt",
    gender: "men",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A Quality t-shirt available in various sizes and colors.",
  },
  {
    name: "Advanced Quality Men T-Shirt",
    gender: "men",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A Advanced Quality t-shirt available in various sizes and colors.",
  },
  {
    name: "Basic Men Pants",
    gender: "men",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 29.99,
    description: "A simple pants available in various sizes and colors.",
  },
  {
    name: "Striped Men Pants",
    gender: "men",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 34.99,
    description: "A striped pants available in various sizes and colors.",
  },
  {
    name: "Quality Men Pants",
    gender: "men",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A Quality pants available in various sizes and colors.",
  },
  {
    name: "Advanced Quality Men Pants",
    gender: "men",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A Advanced Quality pants available in various sizes and colors.",
  },

  {
    name: "Basic Men Shoes",
    gender: "men",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 29.99,
    description: "A basic shoes available in various sizes and colors.",
  },
  {
    name: "Striped Men Shoes",
    gender: "men",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 34.99,
    description: "A striped shoes available in various sizes and colors.",
  },
  {
    name: "Quality Men Shoes",
    gender: "men",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A quality shoes available in various sizes and colors.",
  },
  {
    name: "Advance Quality Men Shoes",
    gender: "men",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A advance quality shoes available in various sizes and colors.",
  },

  {
    name: "Basic women T-Shirt",
    gender: "women",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],

    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
    ],
    price: 19.99,
    description: "A simple t-shirt available in various sizes and colors.",
  },
  {
    name: "Striped women T-Shirt",
    gender: "women",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],

    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 19.99,
    description: "A striped t-shirt available in various sizes and colors.",
  },
  {
    name: "Quality women T-Shirt",
    gender: "women",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],

    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A Quality t-shirt available in various sizes and colors.",
  },
  {
    name: "Advanced Quality women T-Shirt",
    gender: "women",
    productCategory: "tshirt",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/201/7108/5026_CLASSIC_TEE_SAND__57157.1724968871.jpg?c=1",
    ],

    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A Advanced Quality t-shirt available in various sizes and colors.",
  },
  {
    name: "Basic women Pants",
    gender: "women",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 29.99,
    description: "A simple pants available in various sizes and colors.",
  },
  {
    name: "Striped women Pants",
    gender: "women",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 34.99,
    description: "A striped pants available in various sizes and colors.",
  },
  {
    name: "Quality women Pants",
    gender: "women",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A Quality pants available in various sizes and colors.",
  },
  {
    name: "Advanced Quality women Pants",
    gender: "women",
    productCategory: "pants",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/668/17826/5930_STRAIGHT_PANTS_KHAKI__39546.1724895305.jpg?c=1",
    ],
    variations: [
      { size: "S", color: "Red", stock: 10 },
      { size: "M", color: "Red", stock: 15 },
      { size: "L", color: "Red", stock: 5 },
      { size: "XL", color: "Red", stock: 5 },
      { size: "2XL", color: "Red", stock: 5 },
      { size: "3XL", color: "Red", stock: 5 },
      { size: "S", color: "Blue", stock: 12 },
      { size: "M", color: "Blue", stock: 4 },
      { size: "L", color: "Blue", stock: 4 },
      { size: "XL", color: "Blue", stock: 12 },
      { size: "2XL", color: "Blue", stock: 12 },
      { size: "3XL", color: "Blue", stock: 12 },
      { size: "S", color: "Orange", stock: 12 },
      { size: "M", color: "Orange", stock: 4 },
      { size: "L", color: "Orange", stock: 4 },
      { size: "XL", color: "Orange", stock: 12 },
      { size: "2XL", color: "Orange", stock: 12 },
      { size: "3XL", color: "Orange", stock: 12 },
      { size: "S", color: "White", stock: 12 },
      { size: "M", color: "White", stock: 4 },
      { size: "L", color: "White", stock: 4 },
      { size: "XL", color: "White", stock: 12 },
      { size: "2XL", color: "White", stock: 12 },
      { size: "3XL", color: "White", stock: 12 },
      { size: "S", color: "Green", stock: 12 },
      { size: "M", color: "Green", stock: 4 },
      { size: "L", color: "Green", stock: 4 },
      { size: "XL", color: "Green", stock: 12 },
      { size: "2XL", color: "Green", stock: 12 },
      { size: "3XL", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A Advanced Quality pants available in various sizes and colors.",
  },

  {
    name: "Basic women Shoes",
    gender: "women",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 29.99,
    description: "A basic shoes available in various sizes and colors.",
  },
  {
    name: "Striped women Shoes",
    gender: "women",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 34.99,
    description: "A striped shoes available in various sizes and colors.",
  },
  {
    name: "Quality women Shoes",
    gender: "women",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 39.99,
    description: "A quality shoes available in various sizes and colors.",
  },
  {
    name: "Advance Quality women Shoes",
    gender: "women",
    productCategory: "shoes",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/640w/products/676/8862/1210_RELAX_STRIPE_SOCKS_FRONT__93644.1.jpg",
    ],
    variations: [
      { size: "38", color: "Red", stock: 10 },
      { size: "39", color: "Red", stock: 15 },
      { size: "40", color: "Red", stock: 5 },
      { size: "41", color: "Red", stock: 5 },
      { size: "42", color: "Red", stock: 5 },
      { size: "43", color: "Red", stock: 5 },
      { size: "38", color: "Blue", stock: 12 },
      { size: "39", color: "Blue", stock: 4 },
      { size: "40", color: "Blue", stock: 4 },
      { size: "41", color: "Blue", stock: 12 },
      { size: "42", color: "Blue", stock: 12 },
      { size: "43", color: "Blue", stock: 12 },
      { size: "38", color: "Orange", stock: 12 },
      { size: "39", color: "Orange", stock: 4 },
      { size: "40", color: "Orange", stock: 4 },
      { size: "41", color: "Orange", stock: 12 },
      { size: "42", color: "Orange", stock: 12 },
      { size: "43", color: "Orange", stock: 12 },
      { size: "38", color: "White", stock: 12 },
      { size: "39", color: "White", stock: 4 },
      { size: "40", color: "White", stock: 4 },
      { size: "41", color: "White", stock: 12 },
      { size: "42", color: "White", stock: 12 },
      { size: "43", color: "White", stock: 12 },
      { size: "38", color: "Green", stock: 12 },
      { size: "39", color: "Green", stock: 4 },
      { size: "40", color: "Green", stock: 4 },
      { size: "41", color: "Green", stock: 12 },
      { size: "42", color: "Green", stock: 12 },
      { size: "43", color: "Green", stock: 12 },
    ],
    price: 49.99,
    description:
      "A advance quality shoes available in various sizes and colors.",
  },

  {
    name: "Stylish Hat",
    gender: "unisex",
    productCategory: "hat",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
    ],
    variations: [
      { size: "one size", color: "Black", stock: 20 },
      { size: "one size", color: "White", stock: 10 },
    ],
    price: 24.99,
    description: "One size fits all stylish hat available in multiple colors.",
  },
  {
    name: "Striped Hat",
    gender: "unisex",
    productCategory: "hat",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
    ],
    variations: [
      { size: "one size", color: "Black", stock: 20 },
      { size: "one size", color: "White", stock: 10 },
    ],
    price: 24.99,
    description: "One size fits all striped hat available in multiple colors.",
  },
  {
    name: "Quality Hat",
    gender: "unisex",
    productCategory: "hat",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
    ],
    variations: [
      { size: "one size", color: "Black", stock: 20 },
      { size: "one size", color: "White", stock: 10 },
    ],
    price: 24.99,
    description: "One size fits all Quality hat available in multiple colors.",
  },
  {
    name: "Advance Quality Hat",
    gender: "unisex",
    productCategory: "hat",
    images: [
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
      "https://cdn11.bigcommerce.com/s-hsi95a83fz/images/stencil/1500w/products/901/15166/1133_ACCESS_ACTIVE_CAP_BONE_FRONT__82657.1717123186.jpg?c=1",
    ],
    variations: [
      { size: "one size", color: "Black", stock: 20 },
      { size: "one size", color: "White", stock: 10 },
    ],
    price: 24.99,
    description:
      "One size fits all Advance Quality hat available in multiple colors.",
  },
];
